Revert "ENH: CLI env runs with typing.TYPE_CHECKING = True"
This reverts commit 2fc6315943a0ae04223401983e641813985e5cd9.

It appears things begin to fall appart. This line would normally
be hidden by `if TYPE_CHECKING:`, because type checkers don't
fail with circular imports!

Refs: https://github.com/pdoc3/pdoc/issues/460
```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.13/x64/bin/pdoc3", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/runner/work/pdoc/pdoc/pdoc/cli.py", line 559, in main
    modules = [pdoc.Module(module, docfilter=docfilter,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/pdoc/pdoc/pdoc/cli.py", line 559, in <listcomp>
    modules = [pdoc.Module(module, docfilter=docfilter,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/pdoc/pdoc/pdoc/__init__.py", line 677, in __init__
    super().__init__(module.__name__, self, module)
  File "/home/runner/work/pdoc/pdoc/pdoc/__init__.py", line 547, in __init__
    from pdoc.html_helpers import _ToMarkdown
  File "/home/runner/work/pdoc/pdoc/pdoc/html_helpers.py", line 16, in <module>
    import markdown
  File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/markdown/__init__.py", line 42, in <module>
    from .core import Markdown, markdown, markdownFromFile
  File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/markdown/core.py", line 27, in <module>
    from . import util
  File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/markdown/util.py", line 35, in <module>
    from markdown import Markdown
ImportError: cannot import name 'Markdown' from partially initialized module 'markdown' (most likely due to a circular import) (/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/markdown/__init__.py)
```