pdoc.Function.params: Simplify computing positional parameters
It's impossible for a positional parameter with no default value to follow one
which has a default value:

>>> def f(x, y=1, z): pass

SyntaxError: non-default argument follows default argument